version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecocoleta-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: EcoColeta.Api/Dockerfile
    container_name: ecocoleta-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=EcoColetaDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

volumes:
  sqldata:
