// <auto-generated />
using System;
using EcoColeta.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoColeta.Api.Migrations
{
    [DbContext(typeof(EcoColetaDbContext))]
    partial class EcoColetaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoColeta.Api.Models.AlertaColeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int>("PontoColetaId")
                        .HasColumnType("int");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PontoColetaId");

                    b.ToTable("AlertasColeta");
                });

            modelBuilder.Entity("EcoColeta.Api.Models.DestinacaoResiduo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("InstrucoesDescarte")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Reciclavel")
                        .HasColumnType("bit");

                    b.Property<string>("RiscoAmbiental")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TipoResiduo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoResiduo")
                        .IsUnique();

                    b.ToTable("DestinacoesResiduos");
                });

            modelBuilder.Entity("EcoColeta.Api.Models.PontoColeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CapacidadeMaximaKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("OcupacaoAtualKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoResiduoAceito")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cidade");

                    b.HasIndex("TipoResiduoAceito");

                    b.ToTable("PontosColeta");
                });

            modelBuilder.Entity("EcoColeta.Api.Models.RegistroResiduo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PontoColetaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoResiduo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PontoColetaId");

                    b.ToTable("RegistrosResiduos");
                });

            modelBuilder.Entity("EcoColeta.Api.Models.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UsuariosSistema");
                });

            modelBuilder.Entity("EcoColeta.Api.Models.AlertaColeta", b =>
                {
                    b.HasOne("EcoColeta.Api.Models.PontoColeta", "PontoColeta")
                        .WithMany("Alertas")
                        .HasForeignKey("PontoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PontoColeta");
                });

            modelBuilder.Entity("EcoColeta.Api.Models.RegistroResiduo", b =>
                {
                    b.HasOne("EcoColeta.Api.Models.PontoColeta", "PontoColeta")
                        .WithMany("Registros")
                        .HasForeignKey("PontoColetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PontoColeta");
                });

            modelBuilder.Entity("EcoColeta.Api.Models.PontoColeta", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
